language: python
python:
  - "3.6"
  - "3.7-dev"
# command to install dependencies
install:
  - pip install black
  - pip install -q -r requirements.txt
  - python setup.py install
  - sudo rm -f /etc/boto.cfg
# command to run tests
script:
  - black --fast --check ptavitm/.
  - black --fast --check examples/.
  - black --fast --check tests/.
  - pytest --cov=ptavitm
after_success:
  - codecov
